image: 
- Ubuntu1804

environment:
  major: 1
  minor: 0
  app_version: '$(major).$(minor).$(APPVEYOR_BUILD_NUMBER)'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  assembly_version: '$(app_version)'
  file_version: '$(app_version)'
  informational_version: '$(app_version)'

build_script:
  - sh: chmod ugo+x buildLinux.sh
  - sh: ./buildLinux.sh Ubuntu18 $app_version

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - git submodule update --init --recursive
  - nuget sources add -name cpptoolbox -source https://ci.appveyor.com/nuget/ospsuite-cpp-toolbox
#  - ps: (get-content src\OSPSuite.SimModelNative\version.h) | foreach-object {$_ -replace "RELEASE 0", "RELEASE $env:RELEASE" -replace "MAJOR 0", "MAJOR $env:MAJOR" -replace "MINOR 0", "MINOR $env:MINOR" -replace "BUILD 0", "BUILD $env:APPVEYOR_BUILD_NUMBER"} | set-content src\OSPSuite.SimModelNative\version.h
  - sh: nuget install packages.config -OutputDirectory packages -ExcludeVersion

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

skip_commits:
  files:
    - "*.md"

after_build:
#  - cmd: nuget pack src\OSPSuite.CPP-Toolbox\OSPSuite.CPP-Toolbox.nuspec -version %app_version%
#  - sh: nuget pack src/OSPSuite.CPP-Toolbox/OSPSuite.CPP-Toolbox_Ubuntu18.nuspec -version $app_version
#  - ps: Get-ChildItem .\OSPSuite.CPP-Toolbox*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }


